### ISSUE TITLE
Knock Off deletes an item

### ISSUE THREAD

**Issue by EaZynite** [phantombass/Pokemon-Grueling-Gold-v20.1#912]
Hello,

I've come across an error. In a battle against an NPC, my opponent used Knock Off on my Charizard, which was holding Charizardite Y. Not only was the Charizardite Y taken away from the Charizard, but it didn't even return to my inventory. Both of these things shouldn't happen in my opinion. However, Charizardite Y is now removed from my game and my best mega evolution so far is gone.
At the very least, can this item be put back into the inventory using some sort of cheat?

Thank you for the answer.

**Comment by phantombass** [comment]
> Hello,
> 
> I've come across an error. In a battle against an NPC, my opponent used Knock Off on my Charizard, which was holding Charizardite Y. Not only was the Charizardite Y taken away from the Charizard, but it didn't even return to my inventory. Both of these things shouldn't happen in my opinion. However, Charizardite Y is now removed from my game and my best mega evolution so far is gone. At the very least, can this item be put back into the inventory using some sort of cheat?
> 
> Thank you for the answer.

This is a known issue. There's a deliveryman in each Mart that shows up if an item goes missing like that and he should give back all missing items

**Comment by EaZynite** [comment]
Unfortunately, it didn't help. I have visited every Mart in the Johto region and have not found the described deliveryman in any of them. Just to be sure, I went through all my pokemons and rechecked my entire inventory but Charizardite Y is still missing. I can give Charizardite X to Charizard and it works properly. Is there any other way?

**Comment by EaZynite** [comment]
> > Hello,
> > I've come across an error. In a battle against an NPC, my opponent used Knock Off on my Charizard, which was holding Charizardite Y. Not only was the Charizardite Y taken away from the Charizard, but it didn't even return to my inventory. Both of these things shouldn't happen in my opinion. However, Charizardite Y is now removed from my game and my best mega evolution so far is gone. At the very least, can this item be put back into the inventory using some sort of cheat?
> > Thank you for the answer.
> 
> This is a known issue. There's a deliveryman in each Mart that shows up if an item goes missing like that and he should give back all missing items

Unfortunately, it didn't help. I have visited every Mart in the Johto region and have not found the described deliveryman in any of them. Just to be sure, I went through all my pokemons and rechecked my entire inventory but Charizardite Y is still missing. I can give Charizardite X to Charizard and it works properly. Is there any other way?

**Comment by phantombass** [comment]
> > > Hello,
> > > I've come across an error. In a battle against an NPC, my opponent used Knock Off on my Charizard, which was holding Charizardite Y. Not only was the Charizardite Y taken away from the Charizard, but it didn't even return to my inventory. Both of these things shouldn't happen in my opinion. However, Charizardite Y is now removed from my game and my best mega evolution so far is gone. At the very least, can this item be put back into the inventory using some sort of cheat?
> > > Thank you for the answer.
> > 
> > 
> > This is a known issue. There's a deliveryman in each Mart that shows up if an item goes missing like that and he should give back all missing items
> 
> Unfortunately, it didn't help. I have visited every Mart in the Johto region and have not found the described deliveryman in any of them. Just to be sure, I went through all my pokemons and rechecked my entire inventory but Charizardite Y is still missing. I can give Charizardite X to Charizard and it works properly. Is there any other way?

What version of the game are you on?

**Comment by EaZynite** [comment]
> > > > Hello,
> > > > I've come across an error. In a battle against an NPC, my opponent used Knock Off on my Charizard, which was holding Charizardite Y. Not only was the Charizardite Y taken away from the Charizard, but it didn't even return to my inventory. Both of these things shouldn't happen in my opinion. However, Charizardite Y is now removed from my game and my best mega evolution so far is gone. At the very least, can this item be put back into the inventory using some sort of cheat?
> > > > Thank you for the answer.
> > > 
> > > 
> > > This is a known issue. There's a deliveryman in each Mart that shows up if an item goes missing like that and he should give back all missing items
> > 
> > 
> > Unfortunately, it didn't help. I have visited every Mart in the Johto region and have not found the described deliveryman in any of them. Just to be sure, I went through all my pokemons and rechecked my entire inventory but Charizardite Y is still missing. I can give Charizardite X to Charizard and it works properly. Is there any other way?
> 
> What version of the game are you on?

3.2.11

**Comment by phantombass** [comment]
> > > > > Hello,
> > > > > I've come across an error. In a battle against an NPC, my opponent used Knock Off on my Charizard, which was holding Charizardite Y. Not only was the Charizardite Y taken away from the Charizard, but it didn't even return to my inventory. Both of these things shouldn't happen in my opinion. However, Charizardite Y is now removed from my game and my best mega evolution so far is gone. At the very least, can this item be put back into the inventory using some sort of cheat?
> > > > > Thank you for the answer.
> > > > 
> > > > 
> > > > This is a known issue. There's a deliveryman in each Mart that shows up if an item goes missing like that and he should give back all missing items
> > > 
> > > 
> > > Unfortunately, it didn't help. I have visited every Mart in the Johto region and have not found the described deliveryman in any of them. Just to be sure, I went through all my pokemons and rechecked my entire inventory but Charizardite Y is still missing. I can give Charizardite X to Charizard and it works properly. Is there any other way?
> > 
> > 
> > What version of the game are you on?
> 
> 3.2.11

Did you check the dept store as well?

**Comment by EaZynite** [comment]
> > > > > > Hello,
> > > > > > I've come across an error. In a battle against an NPC, my opponent used Knock Off on my Charizard, which was holding Charizardite Y. Not only was the Charizardite Y taken away from the Charizard, but it didn't even return to my inventory. Both of these things shouldn't happen in my opinion. However, Charizardite Y is now removed from my game and my best mega evolution so far is gone. At the very least, can this item be put back into the inventory using some sort of cheat?
> > > > > > Thank you for the answer.
> > > > > 
> > > > > 
> > > > > This is a known issue. There's a deliveryman in each Mart that shows up if an item goes missing like that and he should give back all missing items
> > > > 
> > > > 
> > > > Unfortunately, it didn't help. I have visited every Mart in the Johto region and have not found the described deliveryman in any of them. Just to be sure, I went through all my pokemons and rechecked my entire inventory but Charizardite Y is still missing. I can give Charizardite X to Charizard and it works properly. Is there any other way?
> > > 
> > > 
> > > What version of the game are you on?
> > 
> > 
> > 3.2.11
> 
> Did you check the dept store as well?

Yes, I did. Just one thought. I might be unsure if the NPC used Knock Off on me during the battle, or if it was a wild Sneasel when I tried to cache him.

**Comment by phantombass** [comment]
> > > > > > > Hello,
> > > > > > > I've come across an error. In a battle against an NPC, my opponent used Knock Off on my Charizard, which was holding Charizardite Y. Not only was the Charizardite Y taken away from the Charizard, but it didn't even return to my inventory. Both of these things shouldn't happen in my opinion. However, Charizardite Y is now removed from my game and my best mega evolution so far is gone. At the very least, can this item be put back into the inventory using some sort of cheat?
> > > > > > > Thank you for the answer.
> > > > > > 
> > > > > > 
> > > > > > This is a known issue. There's a deliveryman in each Mart that shows up if an item goes missing like that and he should give back all missing items
> > > > > 
> > > > > 
> > > > > Unfortunately, it didn't help. I have visited every Mart in the Johto region and have not found the described deliveryman in any of them. Just to be sure, I went through all my pokemons and rechecked my entire inventory but Charizardite Y is still missing. I can give Charizardite X to Charizard and it works properly. Is there any other way?
> > > > 
> > > > 
> > > > What version of the game are you on?
> > > 
> > > 
> > > 3.2.11
> > 
> > 
> > Did you check the dept store as well?
> 
> Yes, I did. Just one thought. I might be unsure if the NPC used Knock Off on me during the battle, or if it was a wild Sneasel when I tried to cache him.

Try completely redownloading the game and see if the deliveryman shows up in the mart. Your save file should be fine.

**Comment by EaZynite** [comment]
> > > > > > > > Hello,
> > > > > > > > I've come across an error. In a battle against an NPC, my opponent used Knock Off on my Charizard, which was holding Charizardite Y. Not only was the Charizardite Y taken away from the Charizard, but it didn't even return to my inventory. Both of these things shouldn't happen in my opinion. However, Charizardite Y is now removed from my game and my best mega evolution so far is gone. At the very least, can this item be put back into the inventory using some sort of cheat?
> > > > > > > > Thank you for the answer.
> > > > > > > 
> > > > > > > 
> > > > > > > This is a known issue. There's a deliveryman in each Mart that shows up if an item goes missing like that and he should give back all missing items
> > > > > > 
> > > > > > 
> > > > > > Unfortunately, it didn't help. I have visited every Mart in the Johto region and have not found the described deliveryman in any of them. Just to be sure, I went through all my pokemons and rechecked my entire inventory but Charizardite Y is still missing. I can give Charizardite X to Charizard and it works properly. Is there any other way?
> > > > > 
> > > > > 
> > > > > What version of the game are you on?
> > > > 
> > > > 
> > > > 3.2.11
> > > 
> > > 
> > > Did you check the dept store as well?
> > 
> > 
> > Yes, I did. Just one thought. I might be unsure if the NPC used Knock Off on me during the battle, or if it was a wild Sneasel when I tried to cache him.
> 
> Try completely redownloading the game and see if the deliveryman shows up in the mart. Your save file should be fine.

Yeah, sadly it didn't help either.

**Comment by EaZynite** [comment]
Also, I found that Kangaskhanite is stored under Items and not Mega Stones.

![image](https://github.com/user-attachments/assets/86275160-1ee2-4022-b8db-6f8539c40e70)

**Comment by phantombass** [comment]
> Also, I found that Kangaskhanite is stored under Items and not Mega Stones.
> 
> ![image](https://private-user-images.githubusercontent.com/98807692/382487137-86275160-1ee2-4022-b8db-6f8539c40e70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NjU5NDMsIm5iZiI6MTczMDU2NTY0MywicGF0aCI6Ii85ODgwNzY5Mi8zODI0ODcxMzctODYyNzUxNjAtMWVlMi00MDIyLWI4ZGItNmY4NTM5YzQwZTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDE2NDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ZWIwNDNmZjEyYTA1M2MzMTRmMzI2ZjNjNDY2ZjM5MTZjNGNiMjIxYmYzYWNmYjZjZWJkYzdjYjJlZWYwZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nW9SbcN1fQB7aTgeErOw7ZIPaX8j5peEjxhqpUhKurs)

Ok so I think the issue is you may have patched from an earlier version before the Mega Stones got their own pocket and then weren't in the discord to see the instructions on how to patch to prevent this issue. It's also probably why the Charizardite Y won't show up properly. There isn't anything I can do about this unfortunately so you'd either need to send me your save file over discord or start a new game.

**Comment by EaZynite** [comment]
> > Also, I found that Kangaskhanite is stored under Items and not Mega Stones.
> > ![image](https://private-user-images.githubusercontent.com/98807692/382487137-86275160-1ee2-4022-b8db-6f8539c40e70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NjU5NDMsIm5iZiI6MTczMDU2NTY0MywicGF0aCI6Ii85ODgwNzY5Mi8zODI0ODcxMzctODYyNzUxNjAtMWVlMi00MDIyLWI4ZGItNmY4NTM5YzQwZTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDE2NDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ZWIwNDNmZjEyYTA1M2MzMTRmMzI2ZjNjNDY2ZjM5MTZjNGNiMjIxYmYzYWNmYjZjZWJkYzdjYjJlZWYwZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nW9SbcN1fQB7aTgeErOw7ZIPaX8j5peEjxhqpUhKurs)
> 
> Ok so I think the issue is you may have patched from an earlier version before the Mega Stones got their own pocket and then weren't in the discord to see the instructions on how to patch to prevent this issue. It's also probably why the Charizardite Y won't show up properly. There isn't anything I can do about this unfortunately so you'd either need to send me your save file over discord or start a new game.

I downloaded the game about a month ago from a link in Pokehostel. I skipped a few updates -> I went from 3.2.2 to 3.2.6 or 3.2.7 directly). I DM'd you on Discord to ask where the save file is stored so I could send it to you.
